name: osc
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - nibabel
  - simpleitk
  - scikit-image
  - jupyterlab
  - pip
  - pip:
      - huggingface_hub
      - pymupdf
